try{console.log("Внутри try до myVar"),myVar,console.log("Внутри try после myVar")}catch(o){console.log("Ошибка!")}console.log("После try...catch");
//# sourceMappingURL=01-try-catch.71855166.js.map
